/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penginapanmaster.Booking;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Army
 */
public class BookingUpdateView extends javax.swing.JDialog {

    BookingTableModel tBooking = new BookingTableModel();
    DatabaseBooking dbBook = new DatabaseBooking(); 
    int ID;
    int ID_Booking;
    long harga, lama;
    Date checkIn, checkOut;
    String class_room;
    String tglcheckIn, tglcheckOut;
    
    public BookingUpdateView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tampildata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooking = new javax.swing.JTable();
        btnPilih = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDBooking = new javax.swing.JTextField();
        txtIDCustomer = new javax.swing.JTextField();
        txtIDRoom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnProses = new javax.swing.JButton();
        dateCheckIn = new com.toedter.calendar.JDateChooser();
        dateCheckOut = new com.toedter.calendar.JDateChooser();
        btnCek = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/olegblack.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 90));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Booking Data");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1000, -1));

        tblBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBooking);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 623, 134));

        btnPilih.setText("Select");
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });
        getContentPane().add(btnPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 80, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel2.setText("ID Booking");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 70, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel3.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel3.setText("ID Customer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 80, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel4.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel4.setText("ID Room");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 60, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel5.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel5.setText("Check In");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 60, -1));

        txtIDBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDBookingActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 111, -1));

        txtIDCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 111, -1));
        getContentPane().add(txtIDRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 111, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel6.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel6.setText("Check Out");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 70, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel7.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel7.setText("Duration");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 60, -1));

        txtLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 111, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel8.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel8.setText("Total");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 40, 20));

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 111, -1));

        btnBatal.setText("Cancel");
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 500, 90, -1));

        btnProses.setText("Process");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 500, 80, -1));
        getContentPane().add(dateCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));
        getContentPane().add(dateCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        btnCek.setText("Check");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });
        getContentPane().add(btnCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 80, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Bookingupdateview.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
        try {
            //ambil baris dimana kursor berada
            int baris = tblBooking.getSelectedRow();
            ID_Booking = (int)tBooking.getValueAt(baris, 0);
            int ID_Customer = (int)tBooking.getValueAt(baris, 1);
            int ID_Room = (int)tBooking.getValueAt(baris, 2);
            int Lama = (int)tBooking.getValueAt(baris, 5);
            int Total = (int)tBooking.getValueAt(baris, 6);
            this.ID_Booking = ID_Booking;
            txtIDBooking.setText(Integer.toString(ID_Booking));
            txtIDCustomer.setText(Integer.toString(ID_Customer));
            txtIDRoom.setText(Integer.toString(ID_Room));
            txtLama.setText(Integer.toString(Lama));
            txtTotal.setText(Integer.toString(Total));
        }

        catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnPilihActionPerformed

    public void tampildata() {
        tBooking.setData(dbBook.tampil_seluruh_booking());
        tblBooking.setModel(tBooking);
    }
    
    private void txtIDBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDBookingActionPerformed

    private void txtIDCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCustomerActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed

        dbBook.update_booking(new Booking(Integer.valueOf(txtIDBooking.getText()), Integer.valueOf(txtIDCustomer.getText()), Integer.valueOf(txtIDRoom.getText()), tglcheckIn,tglcheckOut, Integer.valueOf(txtLama.getText()), Integer.valueOf(txtTotal.getText())));
        JOptionPane.showMessageDialog(null, "Data Berhasil diUpdate");
        setVisible(false);
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat format = new SimpleDateFormat(tampilan);
        tglcheckIn = String.valueOf(format.format(dateCheckIn.getDate()));
        tglcheckOut = String.valueOf(format.format(dateCheckOut.getDate()));
        try{
            SimpleDateFormat df = new SimpleDateFormat(tampilan);
            checkIn = df.parse(tglcheckIn);
            checkOut = df.parse(tglcheckOut);
            long pinjam1 = checkIn.getTime();
            long kembali1 = checkOut.getTime();
            long diff = kembali1-pinjam1;
            lama = diff/(24*60*60*1000);
            txtLama.setText(Long.toString(lama));
            Booking bk = dbBook.selectBooking(ID_Booking);
            switch (bk.getClass_room()) {
                case "VIP"          : harga = 1000000;
                                      break;
                case "Family"       : harga = 750000;
                                      break;
                case "Single Bad"   : harga = 250000;
                                      break;
                case "Double Bad"   : harga = 500000;
                                      break;
            }
            long total = harga * lama;
            txtTotal.setText(Long.toString(total));
        }
        catch (Exception e){
                System.out.println(""+ e.getMessage());
          }
        System.out.println(tglcheckIn);
        System.out.println(tglcheckOut);
    }//GEN-LAST:event_btnCekActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLamaActionPerformed

    public void pilih_Room() {
        try {
            //ambil baris dimana kursor berada
            int baris = tblBooking.getSelectedRow();
            int ID_Room = (int)tBooking.getValueAt(baris, 2);
        } 
        
        catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnPilih;
    private javax.swing.JButton btnProses;
    private com.toedter.calendar.JDateChooser dateCheckIn;
    private com.toedter.calendar.JDateChooser dateCheckOut;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBooking;
    private javax.swing.JTextField txtIDBooking;
    private javax.swing.JTextField txtIDCustomer;
    private javax.swing.JTextField txtIDRoom;
    private javax.swing.JTextField txtLama;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
