/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penginapanmaster.Booking;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import penginapanmaster.customer.Customer;
import penginapanmaster.customer.DatabaseCustomer;
import penginapanmaster.room.DatabaseRoom;
import penginapanmaster.room.RoomTableModel;

/**
 *
 * @author Army
 */
public class BookingView extends javax.swing.JFrame {

    int ID;
    long harga, lama;
    Date checkIn, checkOut;
    String class_room;
    String tglcheckIn, tglcheckOut;
    DatabaseCustomer dbCus = new DatabaseCustomer();
    DatabaseRoom dbRoom = new DatabaseRoom();
    DatabaseBooking dbBooking = new DatabaseBooking();
    RoomTableModel tRoom = new RoomTableModel();
    BookingTableModel tBooking = new BookingTableModel();
    
    public BookingView() {
        initComponents();
        tampilusedclass();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNoIdentitas = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbClassRoom = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRoom = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtUsia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        cbJK = new javax.swing.JComboBox<>();
        btnProses = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        dateCheckIn = new com.toedter.calendar.JDateChooser();
        dateCheckOut = new com.toedter.calendar.JDateChooser();
        txtLama = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/award.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(870, 10, 120, 80);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/olegwhite.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 140, 110);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setText("Booking Menu");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 30, 290, 32);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 160, 50, 20);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel3.setText("Identity Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 210, 90, 20);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel4.setText("Address");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 370, 50, 20);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 310, 60, 20);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel6.setText("Email");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 260, 60, 20);

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNama);
        txtNama.setBounds(120, 180, 313, 20);

        txtNoIdentitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoIdentitasActionPerformed(evt);
            }
        });
        jPanel1.add(txtNoIdentitas);
        txtNoIdentitas.setBounds(120, 230, 247, 20);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(120, 280, 313, 20);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel8.setText("Room");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(490, 170, 40, 20);

        cbClassRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "Family", "Singel Bad", "Double Bad" }));
        cbClassRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClassRoomActionPerformed(evt);
            }
        });
        jPanel1.add(cbClassRoom);
        cbClassRoom.setBounds(490, 190, 79, 20);

        tblRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRoom);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(492, 220, 400, 110);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel9.setText("Age");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 310, 50, 15);

        txtUsia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsiaActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsia);
        txtUsia.setBounds(200, 330, 40, 30);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel10.setText("Check In");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(490, 350, 42, 20);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel11.setText("Check Out");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(730, 350, 60, 20);

        btnCari.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        btnCari.setText("Search the Room");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari);
        btnCari.setBounds(730, 190, 130, 23);

        cbJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));
        jPanel1.add(cbJK);
        cbJK.setBounds(120, 330, 50, 30);

        btnProses.setText("Process");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        jPanel1.add(btnProses);
        btnProses.setBounds(650, 500, 86, 23);

        btnBatal.setText("Cancel");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal);
        btnBatal.setBounds(800, 500, 80, 23);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(120, 390, 313, 100);
        jPanel1.add(dateCheckIn);
        dateCheckIn.setBounds(490, 370, 166, 20);
        jPanel1.add(dateCheckOut);
        dateCheckOut.setBounds(730, 370, 166, 20);

        txtLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtLama);
        txtLama.setBounds(570, 430, 70, 20);

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHarga);
        txtHarga.setBounds(730, 430, 166, 20);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jLabel7.setText("IDR");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(730, 410, 18, 15);

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(490, 423, 70, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/booking.jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 1000, 600);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        pilih_Room();
        String JK = (String)cbJK.getSelectedItem();
        System.out.println(JK);
        int l = (int) lama;
        int h = (int) harga;
        dbCus.tambah_customer(new Customer(txtNama.getText(), txtNoIdentitas.getText(),txtAlamat.getText(),JK,txtEmail.getText(),txtUsia.getText()));
        dbBooking.tambah_booking(new Booking(dbCus.getId_customer(), ID,tglcheckIn,tglcheckOut,l,h));
        dbRoom.status_booked(ID);
        JOptionPane.showMessageDialog(null, "Room Sucesfull to Booked");
        setVisible(false);
        cek();
    }//GEN-LAST:event_btnProsesActionPerformed

    public boolean cek(){
        return true;
    }
    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void cbClassRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClassRoomActionPerformed
        
    }//GEN-LAST:event_cbClassRoomActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        refreshData();
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLamaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat format = new SimpleDateFormat(tampilan);
        tglcheckIn = String.valueOf(format.format(dateCheckIn.getDate()));
        tglcheckOut = String.valueOf(format.format(dateCheckOut.getDate()));
//        txtHarga.setText(Long.toString(10000));
        try{
            SimpleDateFormat df = new SimpleDateFormat(tampilan);
            checkIn = df.parse(tglcheckIn);
            checkOut = df.parse(tglcheckOut);
            long pinjam1 = checkIn.getTime();
            long kembali1 = checkOut.getTime();
            long diff = kembali1-pinjam1;
            lama = diff/(24*60*60*1000);
            txtLama.setText(Long.toString(lama)+" Hari");
            
            pilih_Room();
            switch (class_room) {
                case "VIP"          : harga = 1000000;
                                      break;
                case "Family"       : harga = 750000;
                                      break;
                case "Single Bad"   : harga = 250000;
                                      break;
                case "Double Bad"   : harga = 500000;
                                      break;
            }
            long total = harga * lama;
            txtHarga.setText(Long.toString(total));
    }
        catch (Exception e){
                System.out.println(""+ e.getMessage());
          }
        System.out.println(tglcheckIn);
        System.out.println(tglcheckOut);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNoIdentitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoIdentitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoIdentitasActionPerformed

    private void txtUsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsiaActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    public void tampilusedclass(){
        String ClassRoom = (String)cbClassRoom.getSelectedItem();
        tRoom.setData(dbRoom.tampil_class_used(ClassRoom));
        tblRoom.setModel(tRoom); 
    }
    
    public void refreshData(){
        String ClassRoom = (String)cbClassRoom.getSelectedItem();
        tRoom.setData(dbRoom.tampil_class_used(ClassRoom));
        tRoom.fireTableDataChanged();
        tblRoom.changeSelection(0, 0, false, false);
    }
    
    public void pilih_Room() {
        try {
            //ambil baris dimana kursor berada
            int baris = tblRoom.getSelectedRow();
            ID = (int)tRoom.getValueAt(baris, 0);
            class_room = (String)tRoom.getValueAt(baris, 2);
        } 
        
        catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnProses;
    public javax.swing.JComboBox<String> cbClassRoom;
    public javax.swing.JComboBox<String> cbJK;
    public com.toedter.calendar.JDateChooser dateCheckIn;
    public com.toedter.calendar.JDateChooser dateCheckOut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblRoom;
    public javax.swing.JTextArea txtAlamat;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtHarga;
    public javax.swing.JTextField txtLama;
    public javax.swing.JTextField txtNama;
    public javax.swing.JTextField txtNoIdentitas;
    public javax.swing.JTextField txtUsia;
    // End of variables declaration//GEN-END:variables
}
