/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package penginapanmaster;

import penginapanmaster.Booking.BookingPresenter;
import penginapanmaster.customer.CustomerPresenter;
import penginapanmaster.room.RoomPresenter;

/**
 *
 * @author Lukman
 */
public class AdminControlPanel extends javax.swing.JFrame {

    /** Creates new form AdminControlPanel */
    public AdminControlPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toCustomerBtn = new javax.swing.JButton();
        toBookingBtn = new javax.swing.JButton();
        toRoomBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toCustomerBtn.setText("Customer");
        toCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCustomerBtnActionPerformed(evt);
            }
        });

        toBookingBtn.setText("Booking");
        toBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBookingBtnActionPerformed(evt);
            }
        });

        toRoomBtn.setText("Room");
        toRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toRoomBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(toCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(toBookingBtn)
                .addGap(45, 45, 45)
                .addComponent(toRoomBtn)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toCustomerBtn)
                    .addComponent(toBookingBtn)
                    .addComponent(toRoomBtn))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCustomerBtnActionPerformed
        // TODO add your handling code here:
        CustomerPresenter.getCustomer();
    }//GEN-LAST:event_toCustomerBtnActionPerformed

    private void toBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBookingBtnActionPerformed
        // TODO add your handling code here:
        BookingPresenter.getBooking();
    }//GEN-LAST:event_toBookingBtnActionPerformed

    private void toRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRoomBtnActionPerformed
        // TODO add your handling code here:
        RoomPresenter.getRoom();
    }//GEN-LAST:event_toRoomBtnActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton toBookingBtn;
    private javax.swing.JButton toCustomerBtn;
    private javax.swing.JButton toRoomBtn;
    // End of variables declaration//GEN-END:variables

}
