/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package penginapanmaster;

import penginapanmaster.Booking.bookingPresenter;
import penginapanmaster.customer.customerPresenter;
import penginapanmaster.room.roomPresenter;

/**
 *
 * @author Lukman
 */
public class adminControlPanel extends javax.swing.JFrame {

    /** Creates new form AdminControlPanel */
    public adminControlPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        toCustomerBtn = new javax.swing.JButton();
        toBookingBtn = new javax.swing.JButton();
        toRoomBtn = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/olegblack.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 100));

        toCustomerBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        toCustomerBtn.setText("Customer");
        toCustomerBtn.setMinimumSize(new java.awt.Dimension(100, 30));
        toCustomerBtn.setPreferredSize(new java.awt.Dimension(100, 300));
        toCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCustomerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(toCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 240, 130));

        toBookingBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        toBookingBtn.setForeground(java.awt.Color.darkGray);
        toBookingBtn.setText("Booking");
        toBookingBtn.setMaximumSize(new java.awt.Dimension(100, 30));
        toBookingBtn.setMinimumSize(new java.awt.Dimension(100, 30));
        toBookingBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        toBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBookingBtnActionPerformed(evt);
            }
        });
        getContentPane().add(toBookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 240, 130));

        toRoomBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        toRoomBtn.setText("Room");
        toRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toRoomBtnActionPerformed(evt);
            }
        });
        getContentPane().add(toRoomBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 240, 130));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jLabel1.setRequestFocusEnabled(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1000, 600));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel2.setText("Which one data would you like to edit?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 450, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCustomerBtnActionPerformed
        // TODO add your handling code here:
        customerPresenter.getCustomer();
    }//GEN-LAST:event_toCustomerBtnActionPerformed

    private void toBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBookingBtnActionPerformed
        // TODO add your handling code here:
        bookingPresenter.getBookingAdmin();
    }//GEN-LAST:event_toBookingBtnActionPerformed

    private void toRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRoomBtnActionPerformed
        // TODO add your handling code here:
        roomPresenter.getRoom();
    }//GEN-LAST:event_toRoomBtnActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton toBookingBtn;
    private javax.swing.JButton toCustomerBtn;
    private javax.swing.JButton toRoomBtn;
    // End of variables declaration//GEN-END:variables

}
