/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penginapanmaster;

import penginapanmaster.Booking.BookingPresenter;
import penginapanmaster.CheckIn.CheckInPresenter;
import penginapanmaster.CheckOut.CheckOutPresenter;

/**
 *
 * @author Lukman
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCustomerservice = new javax.swing.JButton();
        bHelp = new javax.swing.JButton();
        bAdmin = new javax.swing.JButton();
        bBooking = new javax.swing.JButton();
        bCheckin = new javax.swing.JButton();
        bCheckout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        note2 = new javax.swing.JLabel();
        note1 = new javax.swing.JLabel();
        award = new javax.swing.JLabel();
        olegblack = new javax.swing.JLabel();
        mainview = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        bCustomerservice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/customerservice.png"))); // NOI18N
        bCustomerservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCustomerserviceActionPerformed(evt);
            }
        });
        getContentPane().add(bCustomerservice);
        bCustomerservice.setBounds(620, 350, 110, 110);

        bHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/help.png"))); // NOI18N
        getContentPane().add(bHelp);
        bHelp.setBounds(620, 230, 110, 110);

        bAdmin.setForeground(java.awt.SystemColor.control);
        bAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/admin.png"))); // NOI18N
        bAdmin.setToolTipText("");
        bAdmin.setBorder(null);
        bAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdminActionPerformed(evt);
            }
        });
        getContentPane().add(bAdmin);
        bAdmin.setBounds(250, 350, 110, 110);

        bBooking.setForeground(java.awt.SystemColor.control);
        bBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/booking.png"))); // NOI18N
        bBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBookingActionPerformed(evt);
            }
        });
        getContentPane().add(bBooking);
        bBooking.setBounds(250, 230, 110, 110);

        bCheckin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/checkin.png"))); // NOI18N
        bCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCheckinActionPerformed(evt);
            }
        });
        getContentPane().add(bCheckin);
        bCheckin.setBounds(430, 230, 110, 110);

        bCheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/checkout.png"))); // NOI18N
        bCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCheckoutActionPerformed(evt);
            }
        });
        getContentPane().add(bCheckout);
        bCheckout.setBounds(430, 350, 110, 110);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("your happiness is our goal.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 60, 204, 40);

        note2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        note2.setText("Your comfort is our priority");
        getContentPane().add(note2);
        note2.setBounds(400, 40, 230, 30);

        note1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        note1.setText("Welcome to our Hotel!");
        getContentPane().add(note1);
        note1.setBounds(380, 10, 240, 30);

        award.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/award.png"))); // NOI18N
        getContentPane().add(award);
        award.setBounds(850, 0, 140, 110);

        olegblack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/olegwhite.png"))); // NOI18N
        getContentPane().add(olegblack);
        olegblack.setBounds(10, 0, 140, 110);

        mainview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mainview.jpg"))); // NOI18N
        getContentPane().add(mainview);
        mainview.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdminActionPerformed
        AdminLogin al = new AdminLogin();
        al.setVisible(true);
        //fProses.tnim.setText("");
        //fProses.tnama.setText("");
        //fProses.tjk.setText("");
        //fProses.ttinggi.setText("");
        
    }//GEN-LAST:event_bAdminActionPerformed

    private void bBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBookingActionPerformed
        // TODO add your handling code here:
        BookingPresenter.getBooking();
    }//GEN-LAST:event_bBookingActionPerformed

    private void bCustomerserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCustomerserviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCustomerserviceActionPerformed

    private void bCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCheckinActionPerformed
        // TODO add your handling code here:
        CheckInPresenter.getCheckIn();
    }//GEN-LAST:event_bCheckinActionPerformed

    private void bCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCheckoutActionPerformed
        // TODO add your handling code here:
        CheckOutPresenter.getCheckOut();
    }//GEN-LAST:event_bCheckoutActionPerformed

    
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel award;
    private javax.swing.JButton bAdmin;
    private javax.swing.JButton bBooking;
    private javax.swing.JButton bCheckin;
    private javax.swing.JButton bCheckout;
    private javax.swing.JButton bCustomerservice;
    private javax.swing.JButton bHelp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mainview;
    private javax.swing.JLabel note1;
    private javax.swing.JLabel note2;
    private javax.swing.JLabel olegblack;
    // End of variables declaration//GEN-END:variables
}
