/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penginapanmaster.room;

import javax.swing.JOptionPane;

/**
 *
 * @author Lukman
 */
public class roomEditView extends javax.swing.JDialog {
    databaseRoom db = new databaseRoom();
    int idRoom;
    
     public roomEditView(java.awt.Frame parent, boolean modal,int id, int no_room, String class_room, String status) {
        super(parent, modal);
        initComponents();
        int classR = 0;
        int statusH = 0;
        
        if (null != class_room)switch (class_room) {
            case "VIP":
                classR = 0;
                break;
            case "Family":
                classR = 1;
                break;
            case "Single Bed":
                classR = 2;
                break;
            case "Double Bed":
                classR = 3;
                break;
            default:
                break;
        }
       
        if (null != status)switch (status) {
            case "Booked":
                statusH = 0;
                break;
            case "Used":
                statusH = 1;
                break;
            case "Available":
                statusH = 2;
                break;
            default:
                break;
        }
        
        idRoomLabel.setText(String.valueOf(id));
        noRoomField.setText(String.valueOf(no_room));
        ClassComboBox.setSelectedIndex(classR);
        StatusComboBox.setSelectedIndex(statusH);
    }

    

    
     
    public int getIdRoom() {
        return idRoom;
    }
    /**
     * Creates new form RoomEditView
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idRoomLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        noRoomField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ClassComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        StatusComboBox = new javax.swing.JComboBox<>();
        updateRoom = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/olegblack.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 100));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel6.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel6.setText("Edit Room Data");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 200, 50));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel1.setText("Room ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 70, -1));

        idRoomLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        idRoomLabel.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        idRoomLabel.setText("idroom");
        getContentPane().add(idRoomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 210, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel3.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel3.setText("No. Room");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        noRoomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRoomFieldActionPerformed(evt);
            }
        });
        getContentPane().add(noRoomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 150, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel4.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel4.setText("Status");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 359, 60, -1));

        ClassComboBox.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        ClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\"VIP\"", "\"Family\"", "\"Single Bed\"", "\"Double Bed\"" }));
        ClassComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ClassComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel5.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel5.setText("Class Room");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 80, -1));

        StatusComboBox.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\"Booked\"", "\"Used\"", "\"Available\"" }));
        StatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(StatusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 76, 20));

        updateRoom.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        updateRoom.setText("Update");
        updateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRoomActionPerformed(evt);
            }
        });
        getContentPane().add(updateRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 505, 67, 23));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/roomedit.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noRoomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRoomFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_noRoomFieldActionPerformed

    private void updateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRoomActionPerformed
        // TODO add your handling code here:
        int classR = 0;
        int statusH = 0;
      
          // TODO add your handling code here:
        int id = Integer.valueOf(idRoomLabel.getText());
        int noR = Integer.valueOf(noRoomField.getText());
        int ccb = Integer.valueOf(ClassComboBox.getSelectedIndex());
        int scb = Integer.valueOf(StatusComboBox.getSelectedIndex());
        ccb = ccb + 1;
        scb = scb + 1;
        db.update_room(id,noR,ccb,scb);
        
            
        JOptionPane.showMessageDialog(null, "Data Berhasil ditambah");
        setVisible(false);
    }//GEN-LAST:event_updateRoomActionPerformed

    private void ClassComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassComboBoxActionPerformed

    private void StatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusComboBoxActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ClassComboBox;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JLabel idRoomLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField noRoomField;
    private javax.swing.JButton updateRoom;
    // End of variables declaration//GEN-END:variables
}
